### ISSUE TITLE
Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

### ISSUE THREAD

**Issue by lctone** [atelierdisko/payload-lexical-react-renderer#7]
Can you please help me to fix this one ?

An error occurred when payloadcms updated lexical

![Screenshot 2024-05-08 155113](https://github.com/atelierdisko/payload-lexical-react-renderer/assets/97496024/3ece829e-90ca-4696-9690-8965c6b3835a)

```
 ⨯ node_modules\.pnpm\@atelier-disko+payload-lexical-react-renderer@1.0.4_react-dom@18.3.1_react@18.3.1\node_modules\@atelier-disko\payload-lexical-react-renderer\dist\payload-lexical-react-renderer.es.js (194:1) @ eval
 ⨯ TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@atelier-disko+payload-lexical-react-renderer@1.0.4_react-dom@18.3.1_react@18.3.1/node_modules/@atelier-disko/payload-lexical-react-renderer/dist/payload-lexical-react-renderer.es.js:201:15)
    at le (webpack-internal:///(rsc)/./node_modules/.pnpm/@atelier-disko+payload-lexical-react-renderer@1.0.4_react-dom@18.3.1_react@18.3.1/node_modules/@atelier-disko/payload-lexical-react-renderer/dist/payload-lexical-react-renderer.es.js:632:4)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@atelier-disko+payload-lexical-react-renderer@1.0.4_react-dom@18.3.1_react@18.3.1/node_modules/@atelier-disko/payload-lexical-react-renderer/dist/payload-lexical-react-renderer.es.js:634:26)
    at (rsc)/./node_modules/.pnpm/@atelier-disko+payload-lexical-react-renderer@1.0.4_react-dom@18.3.1_react@18.3.1/node_modules/@atelier-disko/payload-lexical-react-renderer/dist/payload-lexical-react-renderer.es.js (D:\payload\school\sonaedu\.next\server\vendor-chunks\@atelier-disko+payload-lexical-react-renderer@1.0.4_react-dom@18.3.1_react@18.3.1.js:20:1)
    at __webpack_require__ (D:\payload\school\sonaedu\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/components/blog/content-block.tsx:7:103)
    at (rsc)/./src/components/blog/content-block.tsx (D:\payload\school\sonaedu\.next\server\app\(app)\blog\[slug]\page.js:195:1)
    at __webpack_require__ (D:\payload\school\sonaedu\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./src/components/blog/block-render.tsx:7:72)
    at (rsc)/./src/components/blog/block-render.tsx (D:\payload\school\sonaedu\.next\server\app\(app)\blog\[slug]\page.js:184:1) {
type: 'TypeError',
```

**Comment by MendyLanda** [comment]
@lctone I'm experiencing the same issue, were you able to solve it?
I think it has something to do with the react version < 19

**Comment by MendyLanda** [comment]
Temporary solution for those looking here:
If you copy the content of [payloadLexicalReactRenderer.tsx](https://github.com/atelierdisko/payload-lexical-react-renderer/blob/main/src/payloadLexicalReactRenderer.tsx) and use it directly in your project it works fine. 

I don't know what happens exactly, even when overriding the react and react-dom peer deps to match it still gave me this error - when using this package.

**Comment by DaveMitten** [comment]
Had the same issue as you @MendyLanda 

Thanks for the fix. I had to introduce a lot fo fixes into that file too. 

Including if you are to use the <hr/> tag, you need to add this into the function and types or it produces errors again

> Temporary solution for those looking here: If you copy the content of [payloadLexicalReactRenderer.tsx](https://github.com/atelierdisko/payload-lexical-react-renderer/blob/main/src/payloadLexicalReactRenderer.tsx) and use it directly in your project it works fine.
> 
> I don't know what happens exactly, even when overriding the react and react-dom peer deps to match it still gave me this error - when using this package.

**Comment by carstenblt** [comment]
Not working on NextJS 15!

**Comment by mindong2** [comment]
The same issue is repeated in next15.

**Comment by KlotzJesse** [comment]
@schaschjan

Can be fixed by correctly not-bundling react in the vite.config.ts
line 35:
` external: ['react', 'react-dom'],`

to

`external: ["react", /^react\/.*/, "react-dom", /react-dom\/.*/],`
